const data = [
    {
        "count": 20,
        "frequency": 1,
        "id": "caohu",
        "Pinyin": "caohu",
        "Hanzi": "𥕢戶",
        "translation": "mine household, mine operator",
        "def 1": "0",
        "def 2": "0",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "dongzhu",
        "related terms Hanzi": "硐主",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": 0,
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": "0",
        "other": "Yongbei tingzhi ?",
        "diaolong": "0",
        "GJTSJC": null,
        "error": null,
        "field": "2, 3",
        "type": "2, 3"
    },
    {
        "count": 4,
        "frequency": 2,
        "id": "caopi",
        "Pinyin": "caopi",
        "Hanzi": "草皮",
        "translation": "turf, surface ore",
        "def 1": "微夾金砂",
        "def 2": "Wu ca 1823, DKTL ca 1839",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "鋪山檈：散漫無根，雖有所得，不過草皮微鑛。 Yes",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "浮淺而少者曰草皮礦",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": "按：草皮數尺卽得鑛，按完又易其地，是謂草皮鑛也。",
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 51,
        "frequency": 1,
        "id": "dagu",
        "Pinyin": "dagu fenjian",
        "Hanzi": "搭股分尖",
        "translation": "pooled shares, shared workings",
        "def 1": "0",
        "def 2": "0",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": "Presumably partnership company in which investors received exploitation rights according to invested shares",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": 0,
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "2",
        "type": "2"
    },
    {
        "count": 36,
        "frequency": 1,
        "id": "dahua",
        "Pinyin": "dahua",
        "Hanzi": "大花銀礦",
        "translation": "large flowers: galena, low to no silverization",
        "def 1": "其實皆鉛礦",
        "def 2": "0",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "xihua",
        "related terms Hanzi": "細花",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "in entry 銀鑛 yes",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": "uncommon",
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 37,
        "frequency": 2,
        "id": "dimu",
        "Pinyin": "dimu",
        "Hanzi": "底母",
        "translation": "bottom mother, litharge cake",
        "def 1": "鉛浸灰內",
        "def 2": "DKTL ca 1839",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": "litharge cake that forms in the lining of cupellation furnaces",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "罩之渣曰底母，捲而成塊曰鈾團。 Yes",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "common, e.g. QL Yunnan tongzhi juan 11",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 26,
        "frequency": 1,
        "id": "lalong",
        "Pinyin": "lalong cheshui",
        "Hanzi": "拉龍扯水",
        "translation": "working pumps to extract water",
        "def 1": "0",
        "def 2": "Wang 1830s",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "long",
        "related terms Hanzi": "竜",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "0 (entry : 安竜遞扯 as one of 3 draining technologies, the other being bailing by hand 皮袋提背 and driving in a drainage gallery 水洩𥕢硐)",
        "Wang 1830s DKTL": "製水車推送而出，謂之拉龍。",
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": "lalong: Wang Song only",
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 12,
        "frequency": null,
        "id": "gaibei",
        "Pinyin": "gaibei",
        "Hanzi": "蓋被",
        "translation": "getting under the bedding, caving in of a working",
        "def 1": "下開上壓",
        "def 2": "DKTL ca 1839",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "chapter 患 calamities: 蓋被：初開之時不爲立規，硐如篩眼，一經得鑛，競相爭取，旣虞滋事。硬硤窩路尙自無妨，若是鬆塃，勢必覆壓矣。",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 5,
        "frequency": 1,
        "id": "miao",
        "Pinyin": "miao",
        "Hanzi": "苗",
        "translation": "ore sprouts, outcroppings, veins",
        "def 1": "0",
        "def 2": "DKTL ca 1839, Wang 1830s",
        "var Pinyin": "yin, miao, miaoyin, yinxian kuangmiao",
        "var Hanzi": "引, 苗, 苗引, 引線, 鑛苖",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "no",
        "notes": "presumably older expression",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "chapter 引: … 鑛藏於內，苗現於外 yes",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": "yes",
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": "銀苗",
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2, 3"
    },
    {
        "count": "3",
        "frequency": "3",
        "id": "mikuang",
        "Pinyin": "mikuang",
        "Hanzi": "覓礦",
        "translation": "searching ore, prospecting",
        "def 1": "0",
        "def 2": "0",
        "var Pinyin": "mi chang, mi yin",
        "var Hanzi": "覓厰, 覓引",
        "related terms pinyin": "tankuang",
        "related terms Hanzi": "探礦",
        "nsearch": "yes",
        "notes": "in 18th cent sources closer to \"striking ore,\" in 19th century closer to \"prospecting\"",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "0",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "尋苗覔引",
        "TZQS 1779": "廠民覓得綵引 ... 跴覓子廠",
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2, 3"
    },
    {
        "count": 9,
        "frequency": "1",
        "id": "shua",
        "Pinyin": "shua",
        "Hanzi": "刷",
        "translation": "swipe; large, flat orebody",
        "def 1": "礦形成片者",
        "def 2": "Wang 1830s",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": "presumably a rich orebody formed inin a fissure",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "跨刀檈：斜掛進山，忽斷忽續，一得篷座分明，小則成刷，大望成堂 yes",
        "Wang 1830s DKTL": "鑛一片謂之刷",
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": "11",
        "frequency": "1",
        "id": "songhuang",
        "Pinyin": "songhuang",
        "Hanzi": "松塃",
        "translation": "mixture of loose material and ore",
        "def 1": "若土石夾雜",
        "def 2": "DKTL ca 1839, Wang 1830s",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "huang",
        "related terms Hanzi": "塃",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "土曰鬆塃窩路 ... 鬆塃則支設鑲木 yes",
        "Wang 1830s DKTL": "土石夾雜謂之鬆塃",
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": "DKTL, MZXZ",
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 10,
        "frequency": 3,
        "id": "tang",
        "Pinyin": "tang",
        "Hanzi": "堂",
        "translation": "hall; massive orebody",
        "def 1": "𥕢硐寬廣者",
        "def 2": "DKTL ca 1839, Wang 1830s",
        "var Pinyin": "tangkuang, datang",
        "var Hanzi": "堂鑛, 大堂",
        "related terms pinyin": "tang",
        "related terms Hanzi": "塘",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "譬之於瓜，檈者，蔓也。散鑛者，葉也。堂鑛者瓜也。 Yes",
        "Wang 1830s DKTL": "大鑛謂之堂",
        "Ni 1830s DKTL": "yes",
        "Wu ca 1823": "大堂",
        "TZBL 1828": "寬大者爲堂鑛",
        "memorials 1777&1795": "0",
        "TZQS 1779": "yes",
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": null,
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 37,
        "frequency": 1,
        "id": "xihua",
        "Pinyin": "xihua",
        "Hanzi": "細花銀礦",
        "translation": "small flowers; galena, high silverization",
        "def 1": "其實皆鉛礦",
        "def 2": "DKTL ca 1839; Rocher 1879",
        "var Pinyin": "xiaohua",
        "var Hanzi": "小花",
        "related terms pinyin": "dahua",
        "related terms Hanzi": "大花",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "in entry 銀鑛",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 0,
        "frequency": 0,
        "id": "xuan",
        "Pinyin": "xuan",
        "Hanzi": "檈",
        "translation": "ore seam",
        "def 1": 0,
        "def 2": "DKTL ca 1839",
        "var Pinyin": "xian",
        "var Hanzi": "線, 綫",
        "related terms pinyin": "yin",
        "related terms Hanzi": "引",
        "nsearch": "yes",
        "notes": "probably a literarization of xian 綫. See glosse in Wang 1830s",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "chapter 引: … 鑛藏於內，苗現於外，是曰檈引。 … 譬之於瓜，檈者，蔓也。 Yes",
        "Wang 1830s DKTL": "鑛有引線，亦曰鑛苖，亦曰鑛脈。 … 鑛長伏硤謂之檈",
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "0, 0",
        "type": 0
    },
    {
        "count": 5,
        "frequency": "1",
        "id": "yin",
        "Pinyin": "yin",
        "Hanzi": "引",
        "translation": "lead, ore vein",
        "def 1": "0",
        "def 2": "0",
        "var Pinyin": "yin, miao, miaoyin, yinxian kuangmiao",
        "var Hanzi": "引, 苗, 苗引, 引線, 鑛苖",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "no",
        "notes": "presumably Yunnanese expression",
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "chapter 引: … 鑛藏於內，苗現於外，是曰檈引。 Yes",
        "Wang 1830s DKTL": "鑛有引線，亦曰鑛苖，亦曰鑛脈",
        "Ni 1830s DKTL": "引卽鑛苗",
        "Wu ca 1823": "但懼引綫失（銅苗曰引綫）",
        "TZBL 1828": null,
        "memorials 1777&1795": "yes:",
        "TZQS 1779": "yes",
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 0,
        "frequency": 0,
        "id": "yinmiao",
        "Pinyin": "yinmiao",
        "Hanzi": "引苗",
        "translation": "ore vein",
        "def 1": 0,
        "def 2": "TZQS 1779",
        "var Pinyin": "yin, miao, miaoyin, yinxian kuangmiao",
        "var Hanzi": "引, 苗, 苗引, 引線, 鑛苖",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "yes",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": "必有綵色苗引掛於山石閒, 山遇硤中帶綠或帶𥖎焦明鑛皆爲引苗開",
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 6,
        "frequency": 1,
        "id": "yishan",
        "Pinyin": "yishan you kuang, qianshan you yin",
        "Hanzi": "一山有礦，千山有引",
        "translation": "one mountain with ore, a thousand with outcroppings",
        "def 1": "0",
        "def 2": "0",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "chapter 引: in introduction",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": "DKTL, SGP, MZXZ",
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": 4
    },
    {
        "count": 8,
        "frequency": 1,
        "id": "zhengxuan",
        "Pinyin": "zhengxuan",
        "Hanzi": "正檈",
        "translation": "proper seam",
        "def 1": "漸而得, 乃可進山獲礦",
        "def 2": "0",
        "var Pinyin": "laoxuan",
        "var Hanzi": "老檈",
        "related terms pinyin": "xuan",
        "related terms Hanzi": "檈",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "子檈之鑛薄，老檈之鑛進山。",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 53,
        "frequency": 1,
        "id": "zhusha",
        "Pinyin": "zhusha",
        "Hanzi": "朱砂",
        "translation": "cinnabar ore: a rich silver ore",
        "def 1": "no",
        "def 2": "0",
        "var Pinyin": "0",
        "var Hanzi": "硃砂",
        "related terms pinyin": "0",
        "related terms Hanzi": "0",
        "nsearch": "yes",
        "notes": "probably proustite",
        "Huang 1849": "紅為朱砂硔",
        "DKTL & figs ca 1839 ": "0",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": null,
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": 7,
        "frequency": 1,
        "id": "zixuan",
        "Pinyin": "zixuan",
        "Hanzi": "子檈",
        "translation": "baby seam",
        "def 1": "引之初見",
        "def 2": "DKTL ca 1839",
        "var Pinyin": "0",
        "var Hanzi": "0",
        "related terms pinyin": "xuan",
        "related terms Hanzi": "檈",
        "nsearch": "yes",
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": "子檈之鑛薄，老檈之鑛進山。",
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": "0",
        "TZBL 1828": null,
        "memorials 1777&1795": "0",
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": "nn",
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": "1",
        "type": "2"
    },
    {
        "count": null,
        "frequency": null,
        "id": null,
        "Pinyin": null,
        "Hanzi": null,
        "translation": null,
        "def 1": null,
        "def 2": null,
        "var Pinyin": null,
        "var Hanzi": null,
        "related terms pinyin": null,
        "related terms Hanzi": null,
        "nsearch": null,
        "notes": null,
        "Huang 1849": null,
        "DKTL & figs ca 1839 ": null,
        "Wang 1830s DKTL": null,
        "Ni 1830s DKTL": null,
        "Wu ca 1823": null,
        "TZBL 1828": null,
        "memorials 1777&1795": null,
        "TZQS 1779": null,
        "Wang 1770s QSD": null,
        "Gejiu ca 1710 ": null,
        "Song 1630s ": null,
        "other": null,
        "diaolong": null,
        "GJTSJC": null,
        "error": null,
        "field": null,
        "type": null
    }
];
